/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UploadWidget: typeof import('./src/components/upload-widget.vue')['default']
    UploadWidgetDropzone: typeof import('./src/components/upload-widget-dropzone.vue')['default']
    UploadWidgetHeader: typeof import('./src/components/upload-widget-header.vue')['default']
    UploadWidgetMinimizedButton: typeof import('./src/components/upload-widget-minimized-button.vue')['default']
    UploadWidgetTitle: typeof import('./src/components/upload-widget-title.vue')['default']
    UploadWidgetUploadItem: typeof import('./src/components/upload-widget-upload-item.vue')['default']
    UploadWidgetUploadList: typeof import('./src/components/upload-widget-upload-list.vue')['default']
  }
}
